MODEL:
  ENCODER_LAYERS: 2
  WRI_DEC_LAYERS: 2
  GLY_DEC_LAYERS: 2
  NUM_HEAD_LAYERS: 1
  NUM_IMGS: 15
NUM_GPUS: 1  # TODO, support multi GPUs
SOLVER:
  BASE_LR: 0.0002
  MAX_ITER: 200000
  WARMUP_ITERS: 20000
  TYPE: Adam  # TODO, support optional optimizer
  GRAD_L2_CLIP: 5.0
TRAIN:
  ISTRAIN: True
  IMS_PER_BATCH: 64
  SNAPSHOT_BEGIN: 2000
  SNAPSHOT_ITERS: 4000
  VALIDATE_ITERS: 2000
  VALIDATE_BEGIN: 2000
  SEED: 1001
  IMG_H: 64
  IMG_W: 64
TEST:
  ISTRAIN: False
  IMG_H: 64
  IMG_W: 64
DATA_LOADER:
  NUM_THREADS: 8
  CONCAT_GRID: True
  TYPE: ScriptDataset
  PATH: data
  DATASET: JANPANESE